version: '3.6'
services:
  www:
    image: node:14
    volumes:
      - ./:/srv
    working_dir: /srv
    command: bash -c "npm ci && npm start"
    restart: always
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.frontend.rule=Host:${DOMAIN:-reniferamongus.tymek.cz},www.${DOMAIN:-reniferamongus.tymek.cz}
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.SSLHost=${DOMAIN:-reniferamongus.tymek.cz}
      - traefik.frontend.headers.SSLForceHost=true
      - traefik.docker.network=wan
      - com.ouroboros.enable=true
    networks:
      - wan

networks:
  wan:
    external: true
